# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ab2ec40daac4fb20bc43d528134cf8e8882c254062f8344bc36a3c140ef6b7b609a6d7eb05b6aa438455f6f200b661e1b9305d404b332ed7568d0ee1dbe417d
  shopify_api_key: e14188bdb871e234cf4fcb074aff6655
  shopify_api_secret: eb1a3781e1e90c7ad279b9cb2da29837
  database_url: 'postgresql://postgres@localhost:5432/public_profile_development?pool=5&timeout=5000'

test:
  secret_key_base: XXX
  shopify_api_key: XXX
  shopify_api_secret: XXX
  database_url: 'postgresql://postgres@localhost:5432/public_profile_test?pool=5&timeout=5000'

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  shopify_api_key: <%= ENV['SHOPIFY_API_KEY'] %>
  shopify_api_secret: <%= ENV['SHOPIFY_API_SECRET'] %>
  database_url: <%= ENV['DATABASE_URL'] %>
